INSERT INTO products (name, price, category, image_url, description, stock_quantity, sizes, colors) VALUES
('AFB Cassette Tee — Grey', 45000, 'T-Shirt', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/tshirt-grey-cassette.png', 'African Boy cassette graphic tee in charcoal grey', 25, ARRAY['S','M','L','XL','XXL'], '[{"name":"Charcoal","hex":"#4a4a4a"}]'::jsonb),
('AFB Cassette Tee — Yellow', 45000, 'T-Shirt', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/tshirt-yellow-cassette.png', 'African Boy cassette graphic tee in mustard yellow', 25, ARRAY['S','M','L','XL','XXL'], '[{"name":"Yellow","hex":"#e8a817"}]'::jsonb),
('AFB Splash Tee — Olive', 45000, 'T-Shirt', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/tshirt-olive-splash.png', 'Colorful splash art tee in olive green', 20, ARRAY['S','M','L','XL','XXL'], '[{"name":"Olive","hex":"#8a9a5b"}]'::jsonb),
('AFB Splash Tee — Pink', 45000, 'T-Shirt', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/tshirt-pink-splash.png', 'Colorful splash art tee in baby pink', 20, ARRAY['S','M','L','XL','XXL'], '[{"name":"Pink","hex":"#f4b8c8"}]'::jsonb),
('AFB Red Logo Tee — White', 45000, 'T-Shirt', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/tshirt-white-red.png', 'African Boy red logo cassette tee in white', 25, ARRAY['S','M','L','XL','XXL'], '[{"name":"White","hex":"#f5f5f5"}]'::jsonb),
('AFB Red Logo Tee — Black', 45000, 'T-Shirt', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/tshirt-black-red.png', 'African Boy red logo cassette tee in black', 25, ARRAY['S','M','L','XL','XXL'], '[{"name":"Black","hex":"#1a1a1a"}]'::jsonb),
('AFB Splash Tee — Charcoal', 45000, 'T-Shirt', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/tshirt-grey-splash.png', 'Colorful splash art tee in charcoal grey', 20, ARRAY['S','M','L','XL','XXL'], '[{"name":"Charcoal","hex":"#4a4a4a"}]'::jsonb),
('AFB Collage Tee', 45000, 'T-Shirt', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/tshirt-grey-collage.png', 'African Boy collage art tee in charcoal grey', 20, ARRAY['S','M','L','XL','XXL'], '[{"name":"Charcoal","hex":"#4a4a4a"}]'::jsonb),
('AFB Flames Tee', 45000, 'T-Shirt', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/tshirt-black-flames.png', 'African Boy flames graphic tee in black', 20, ARRAY['S','M','L','XL','XXL'], '[{"name":"Black","hex":"#1a1a1a"}]'::jsonb);