INSERT INTO public.products (name, price, category, image_url, description, stock_quantity, sizes, colors) VALUES
('AFB Classic Badge Cap - Yellow/Black', 20000, 'Caps', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/cap-1.png', 'Premium AFB trucker cap with embroidered badge logo. Yellow and black two-tone design.', 25, ARRAY['One Size'], '[{"name":"Yellow","hex":"#F5C518"},{"name":"Black","hex":"#1a1a1a"}]'::jsonb),
('AFB Graffiti Snapback - White/Teal', 20000, 'Caps', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/cap-2.png', 'Flat brim snapback with bold AFB graffiti-style embroidery. White crown with teal visor.', 25, ARRAY['One Size'], '[{"name":"White","hex":"#f5f5f5"},{"name":"Teal","hex":"#008080"}]'::jsonb),
('AFB Signature Cap - Royal Blue', 20000, 'Caps', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/cap-3.png', 'Clean royal blue dad cap with embroidered AFB logo. Adjustable strap.', 25, ARRAY['One Size'], '[{"name":"Blue","hex":"#2563EB"}]'::jsonb),
('AFB Badge Cap - Burgundy', 20000, 'Caps', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/cap-4.png', 'Burgundy trucker cap with iconic AFB badge patch. Mesh back for breathability.', 25, ARRAY['One Size'], '[{"name":"Burgundy","hex":"#800020"}]'::jsonb),
('AFB Triangle Cap - Navy', 20000, 'Caps', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/cap-5.png', 'Dark navy cap with distinctive AFB triangle logo patch. Clean minimal design.', 25, ARRAY['One Size'], '[{"name":"Navy","hex":"#1b2a4a"}]'::jsonb),
('AFB Graphic Cap - Grey', 20000, 'Caps', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/cap-6.png', 'Grey dad cap with bold AFB graphic print. Street-ready style.', 25, ARRAY['One Size'], '[{"name":"Grey","hex":"#808080"}]'::jsonb),
('AFB Signature Cap - Orange', 20000, 'Caps', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/cap-7.png', 'Vibrant orange cap with embroidered AFB logo. Stand out from the crowd.', 25, ARRAY['One Size'], '[{"name":"Orange","hex":"#EA580C"}]'::jsonb),
('AFB Triangle Cap - Pink', 20000, 'Caps', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/cap-8.png', 'Soft pink cap with AFB triangle logo patch. Premium quality finish.', 25, ARRAY['One Size'], '[{"name":"Pink","hex":"#EC4899"}]'::jsonb),
('AFB Signature Cap - Beige', 20000, 'Caps', 'https://xvsemaahrkymlmqserrf.supabase.co/storage/v1/object/public/products/cap-9.png', 'Neutral beige cap with embroidered AFB logo. Versatile everyday wear.', 25, ARRAY['One Size'], '[{"name":"Beige","hex":"#D2B48C"}]'::jsonb);